---

- name: Ensure k3s initial control plane server is started
  ansible.builtin.service:
    name: k3s
    state: started
    enabled: "{{ k3s_start_on_boot }}"
  register: k3s_service_start_k3s
  failed_when:
    - k3s_service_start_k3s is not succeeded
    - not ansible_check_mode
  when: (k3s_control_node and k3s_controller_list | length == 1)
        or (k3s_primary_control_node and k3s_controller_list | length > 1)
        or k3s_token_cluster_check.stat.exists
  become: "{{ k3s_become }}"
